/**:
  ros__parameters:
    # command_list_yaml: ['PBVS,parking_forkcamera,2.0',
    # 'PBVS,raise_pallet,2.0',
    # 'odom,odom_turn,91.0',
    # 'odom,odom_front,-2.0',
    # 'odom,odom_turn,-91.0',
    # 'PBVS,parking_bodycamera,2.0',
    # 'PBVS,drop_pallet,2.0',
    # 'odom,odom_front,-0.33',
    # 'PBVS,raise_pallet,1.0',
    # 'odom,odom_turn,-92.0',
    # 'odom,odom_front,-2.0',
    # 'odom,odom_turn,90.0',
    # 'PBVS,parking_bodycamera,1.0',
    # 'PBVS,drop_pallet,1.0']

    command_list_yaml: ['TopologyMap,P1',
    'PBVS,parking_forkcamera,2.0',
    'PBVS,raise_pallet,2.0',
    'TopologyMap,P2',
    'PBVS,parking_bodycamera,2.0',
    'PBVS,drop_pallet,2.0',
    'odom,odom_front,-0.31',
    'PBVS,raise_pallet,1.0',
    'TopologyMap,P1',
    'PBVS,parking_bodycamera,1.0',
    'PBVS,drop_pallet,1.0']

    # command_list_yaml: ['TopologyMap,P1',
    # 'odom,odom_front,-0.33',
    # 'TopologyMap,P2']
    
    waypoints: '{"P1": [5.010080337524414, 1.899872064590454, 0.9909603668940082, 0.13415495236961086],
                 "P2": [6.036149978637695, 5.755815505981445, 0.9915192728076967, 0.12995973088190235],
                 "P3": [0.0, 0.0, 0.0, 0.0]}'

    # command [PBVS,parking_forkcamera,layer]   使用牙叉相機對位棧板
    # command [PBVS,parking_bodycamera,layer]   使用車體相機對位貨架
    # command [PBVS,raise_pallet,layer]         叉起layer層的棧板
    # command [PBVS,drop_pallet,layer]          放下棧板在layer層
    # command [odom,odom_front,1.0]             前進 1.0 meter /degree
    # command [odom,odom_front,-1.0]            後退 1.0 meter
    # command [odom,odom_turn,90.0]             左轉 90.0 degree
    # command [odom,odom_turn,-90.0]            右轉 90.0 degree
    # command [TopologyMap,P1]                  導航至P1
    # waypoints: '{"P1": [position.x, position.y ,orientation.z, orientation.w]}'