/**:
  ros__parameters:
    command_list_yaml: ['PBVS,parking_forkcamera,2.0',
    'PBVS,raise_pallet,2.0',
    'odom,odom_turn,91.0',
    'odom,odom_front,-2.0',
    'odom,odom_turn,-91.0',
    'PBVS,parking_bodycamera,2.0',
    'PBVS,drop_pallet,2.0',
    'odom,odom_front,-0.33',
    'PBVS,raise_pallet,1.0',
    'odom,odom_turn,-92.0',
    'odom,odom_front,-2.0',
    'odom,odom_turn,90.0',
    'PBVS,parking_bodycamera,1.0',
    'PBVS,drop_pallet,1.0']

    # command [PBVS,parking_forkcamera,layer]   使用牙叉相機對位棧板
    # command [PBVS,parking_bodycamera,layer]   使用車體相機對位貨架
    # command [PBVS,raise_pallet,layer]         叉起layer層的棧板
    # command [PBVS,drop_pallet,layer]          放下棧板在layer層
    # command [odom,odom_front,1.0]             前進 1.0 meter /degree
    # command [odom,odom_front,-1.0]            後退 1.0 meter
    # command [odom,odom_turn,90.0]             左轉 90.0 degree
    # command [odom,odom_turn,-90.0]            右轉 90.0 degree